### ISSUE TITLE
Link on landing page is broken

### ISSUE THREAD

**Issue by saadman-galib** [planetarium/www.nine-chronicles.dev#103]
In Modding Friendly section, the Mimir link is broken

![image](https://github.com/user-attachments/assets/63aac564-dc23-4385-a9e3-798a4647ef3d)

It is redirecting to a page that is not found. 

![image](https://github.com/user-attachments/assets/b76cb907-0790-49b1-a37d-feba10fbc59b)

The broken link: http://127.0.0.1:5173/general/get-state/get-state-with-mimir-graphql

**Comment by Atralupus** [comment]
Thank you for reporting!
