### ISSUE TITLE
Banana Cake Pop -> Nitro

### ISSUE THREAD

**Issue by Atralupus** [planetarium/www.nine-chronicles.dev#91]
The service name has changed from Banana Cake Pop to Nitro. [Documentation](https://chillicream.com/docs/nitro/explore-the-ui)
Please update our [Document(en)](https://github.com/planetarium/www.nine-chronicles.dev/blob/d55eba18f4b772c42949af903ce3f2546bb9ada6/en/guide/general/get-state/get-state-with-mimir-graphql.md?plain=1#L30) and [Document(ko)](https://github.com/planetarium/www.nine-chronicles.dev/blob/d55eba18f4b772c42949af903ce3f2546bb9ada6/ko/guide/general/get-state/get-state-with-mimir-graphql.md?plain=1#L24) with the new name and link it to https://chillicream.com/docs/nitro/explore-the-ui.

**Comment by mushahidq** [comment]
Hi! I'd like to work on this. Can you please assign it to me?

**Comment by Atralupus** [comment]
> Hi! I'd like to work on this. Can you please assign it to me?

@mushahidq  Sure! I just assigned you to this issue.

---

We're now operating Modathon 2024 (Nine Chronicles Hackathon) with a prize pool about $10,000. If you're interested, please take a look at the following items.🙏
https://nine-chronicles.dev/event/2024modathon
https://planetarium.dev/discord
